import { createServerSupabaseClient } from '@supabase/auth-helpers-nextjs';
import { useSession, useSupabaseClient } from '@supabase/auth-helpers-react';
import type { GetServerSidePropsContext, NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import Header from '../components/Header';
import Image from 'next/image';

export const getServerSideProps = async (ctx: GetServerSidePropsContext) => {
  const supabase = createServerSupabaseClient(ctx);

  const {
    data: { session }
  } = await supabase.auth.getSession();

  // if (!session)
  //   return {
  //     redirect: {
  //       destination: '/signin',
  //       permanent: false
  //     }
  //   };

  return { props: {}}
};

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className="container mx-auto p-4">
        <header></header>
        <h1 className="text-xl mb-4">Worlds</h1>
        <section>
          <Link href={'/worlds/1'}>
            <article className="block max-w-sm bg-white rounded-lg shadow-md hover:bg-gray-100">
              <Image src="/pic1.png" alt="" width="400" height="150" className='border-none'/>
              <h2 className='p-6'>World 1</h2>
            </article>
          </Link>
        </section>
      </main>
    </div>
  );
};

export default Home;
