import { withPageAuth } from '@supabase/auth-helpers-nextjs';
import { useSession, useSupabaseClient } from '@supabase/auth-helpers-react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import Header from '../components/Header';

export const getServerSideProps = withPageAuth({
  redirectTo: '/signin'
});

const Home: NextPage = () => {
  const session = useSession();
  const supabase = useSupabaseClient();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className='container mx-auto py-4'>
        <header></header>
        <h1 className="text-xl mb-4">Worlds</h1>
        <section>
          <Link href={'/worlds/1'}>
            <article className='block max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow-md hover:bg-gray-100'>
              <h2>World 1</h2>
            </article>
          </Link>
        </section>
      </main>
    </div>
  );
};

export default Home;
